'use client';

/**
 * Variant Form Component
 *
 * Form for creating and editing product variants
 */

import React, { useState, useCallback } from 'react';
import dynamic from 'next/dynamic';
import { ProductVariant, CreateProductVariantDto, UpdateProductVariantDto } from '@/lib/api/variants';
import { formatNumber } from '@/lib/utils/number-format';

// Dynamically import EnhancedImageUpload to avoid SSR issues with framer-motion
const EnhancedImageUpload = dynamic(() => import('../products/EnhancedImageUpload'), {
  ssr: false,
  loading: () => <div className="animate-pulse bg-gray-200 h-48 rounded-lg" />,
});

interface VariantFormProps {
  variant?: ProductVariant;
  productPrice?: number;
  onSubmit: (data: CreateProductVariantDto | UpdateProductVariantDto) => Promise<void>;
  onCancel: () => void;
  loading?: boolean;
}

export function VariantForm({ variant, productPrice, onSubmit, onCancel, loading }: VariantFormProps) {
  const [formData, setFormData] = useState({
    name: variant?.name || '',
    sku: variant?.sku || '',
    price: variant?.price !== undefined ? variant.price : productPrice,
    compareAtPrice: variant?.compareAtPrice || undefined,
    inventory: variant?.inventory || 0,
    attributes: variant?.options || {},
    image: variant?.image || '',
    colorHex: variant?.colorHex || '',
    colorName: variant?.colorName || '',
    isAvailable: variant?.isAvailable !== undefined ? variant.isAvailable : true,
    lowStockThreshold: variant?.lowStockThreshold || 5,
  });

  const [newAttributeKey, setNewAttributeKey] = useState('');
  const [newAttributeValue, setNewAttributeValue] = useState('');

  const handleChange = (field: string, value: any) => {
    setFormData({ ...formData, [field]: value });
  };

  // Memoized callback to prevent infinite loop in EnhancedImageUpload
  const handleImageChange = useCallback((urls: string[]) => {
    setFormData((prev) => ({ ...prev, image: urls[0] || '' }));
  }, []);

  const handleAddAttribute = () => {
    if (newAttributeKey && newAttributeValue) {
      handleChange('attributes', {
        ...formData.attributes,
        [newAttributeKey]: newAttributeValue,
      });
      setNewAttributeKey('');
      setNewAttributeValue('');
    }
  };

  const handleRemoveAttribute = (key: string) => {
    const newAttributes = { ...formData.attributes };
    delete newAttributes[key];
    handleChange('attributes', newAttributes);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    // Validation
    if (!formData.name.trim()) {
      alert('Please enter a variant name');
      return;
    }
    // SKU validation removed - SKU is auto-generated by the system
    if (Object.keys(formData.attributes).length === 0) {
      alert('Please add at least one attribute (e.g., size, color)');
      return;
    }

    // Validate price: must be a valid number >= 0, or use productPrice as fallback
    let finalPrice: number | undefined;

    if (typeof formData.price === 'number' && !isNaN(formData.price)) {
      // User entered a price for this variant
      finalPrice = formData.price;
    } else if (typeof productPrice === 'number' && !isNaN(productPrice)) {
      // Inherit from product price
      finalPrice = productPrice;
    } else {
      // No valid price available
      alert('Please enter a variant price. The product does not have a base price to inherit.');
      return;
    }

    if (finalPrice < 0) {
      alert('Price must be 0 or greater');
      return;
    }

    // Validate compareAtPrice if provided
    if (formData.compareAtPrice !== undefined &&
        (isNaN(formData.compareAtPrice) || formData.compareAtPrice < 0)) {
      alert('Compare at price must be a valid number (0 or greater)');
      return;
    }

    try {
      await onSubmit({
        name: formData.name,
        // SKU is NOT included - it's auto-generated by the backend
        price: finalPrice,
        compareAtPrice: formData.compareAtPrice,
        inventory: formData.inventory,
        attributes: formData.attributes,
        // Always include image field when updating (to allow clearing), but only when it has value when creating
        image: formData.image || (variant ? null : undefined), // null to clear on update, undefined to omit on create
        colorHex: formData.colorHex || undefined,
        colorName: formData.colorName || undefined,
        isAvailable: formData.isAvailable,
        lowStockThreshold: formData.lowStockThreshold,
      });
    } catch (error) {
      // Error is handled by parent component
    }
  };

  return (
    <div className="space-y-4">
      {/* Basic Info */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Variant Name <span className="text-red-500">*</span>
          </label>
          <input
            type="text"
            required
            value={formData.name}
            onChange={(e) => handleChange('name', e.target.value)}
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#CBB57B] focus:border-transparent text-sm"
            placeholder="e.g., Medium Black Cotton"
          />
        </div>

        {variant ? (
          // Show SKU as read-only when editing
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              SKU (System Generated - Read Only)
            </label>
            <input
              type="text"
              value={formData.sku}
              disabled
              className="w-full px-3 py-2 border border-gray-300 rounded-lg bg-gray-100 text-gray-600 cursor-not-allowed text-sm"
              title="SKU is system-generated and cannot be modified"
            />
            <p className="text-xs text-gray-500 mt-1">
              SKU is automatically generated and cannot be changed
            </p>
          </div>
        ) : (
          // Hide SKU field when creating new variant
          <div>
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
              <p className="text-sm text-blue-800">
                <strong>SKU will be auto-generated</strong>
              </p>
              <p className="text-xs text-blue-600 mt-1">
                Format: NEXTPIK-V-MM-DD-XXXXXX (e.g., NEXTPIK-V-01-30-000001)
              </p>
            </div>
          </div>
        )}
      </div>

      {/* Attributes */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          Attributes <span className="text-red-500">*</span>
        </label>
        <div className="flex gap-2 mb-2">
          <input
            type="text"
            value={newAttributeKey}
            onChange={(e) => setNewAttributeKey(e.target.value)}
            className="flex-1 px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#CBB57B] focus:border-transparent text-sm"
            placeholder="Attribute (e.g., size, color, material)"
          />
          <input
            type="text"
            value={newAttributeValue}
            onChange={(e) => setNewAttributeValue(e.target.value)}
            onKeyPress={(e) => e.key === 'Enter' && (e.preventDefault(), handleAddAttribute())}
            className="flex-1 px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#CBB57B] focus:border-transparent text-sm"
            placeholder="Value (e.g., M, Black, Cotton)"
          />
          <button
            type="button"
            onClick={handleAddAttribute}
            className="px-4 py-2 bg-gray-100 hover:bg-gray-200 rounded-lg transition-colors text-sm"
          >
            Add
          </button>
        </div>
        <div className="flex flex-wrap gap-2">
          {Object.entries(formData.attributes).map(([key, value]) => (
            <span
              key={key}
              className="px-3 py-1 bg-[#CBB57B] text-black rounded-full text-sm flex items-center gap-2"
            >
              <strong>{key}:</strong> {value}
              <button
                type="button"
                onClick={() => handleRemoveAttribute(key)}
                className="hover:text-red-600 font-bold"
              >
                ×
              </button>
            </span>
          ))}
        </div>
      </div>

      {/* Pricing */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Price (USD) {!productPrice && <span className="text-red-500">*</span>}
          </label>
          <div className="relative">
            <span className="absolute left-3 top-2 text-gray-500 text-sm">$</span>
            <input
              type="number"
              min="0"
              step="0.01"
              value={formData.price !== undefined ? formData.price : ''}
              onChange={(e) => {
                const value = e.target.value === '' ? undefined : parseFloat(e.target.value);
                handleChange('price', value !== undefined && !isNaN(value) ? value : undefined);
              }}
              className={`w-full pl-8 pr-3 py-2 border rounded-lg focus:ring-2 focus:ring-[#CBB57B] focus:border-transparent text-sm ${
                !productPrice && !formData.price ? 'border-red-300 bg-red-50' : 'border-gray-300'
              }`}
              placeholder={
                productPrice
                  ? `Leave empty to inherit ${formatNumber(productPrice)}`
                  : 'Required - enter variant price'
              }
              required={!productPrice}
            />
          </div>
          <p className={`text-xs mt-1 ${!productPrice ? 'text-red-600 font-medium' : 'text-gray-500'}`}>
            {productPrice
              ? `Leave empty to inherit product price of ${formatNumber(productPrice)}`
              : 'Product has no base price - you must enter a price for this variant'}
          </p>
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Compare At Price (USD)
          </label>
          <div className="relative">
            <span className="absolute left-3 top-2 text-gray-500 text-sm">$</span>
            <input
              type="number"
              min="0"
              step="0.01"
              value={formData.compareAtPrice !== undefined ? formData.compareAtPrice : ''}
              onChange={(e) => {
                const value = e.target.value === '' ? undefined : parseFloat(e.target.value);
                handleChange('compareAtPrice', value !== undefined && !isNaN(value) ? value : undefined);
              }}
              className="w-full pl-8 pr-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#CBB57B] focus:border-transparent text-sm"
              placeholder="0.00"
            />
          </div>
        </div>
      </div>

      {/* Inventory */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Inventory <span className="text-red-500">*</span>
          </label>
          <input
            type="number"
            required
            min="0"
            value={formData.inventory}
            onChange={(e) => handleChange('inventory', parseInt(e.target.value) || 0)}
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#CBB57B] focus:border-transparent text-sm"
            placeholder="0"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Low Stock Threshold
          </label>
          <input
            type="number"
            min="1"
            value={formData.lowStockThreshold}
            onChange={(e) => handleChange('lowStockThreshold', parseInt(e.target.value) || 5)}
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#CBB57B] focus:border-transparent text-sm"
            placeholder="5"
          />
          <p className="text-xs text-gray-500 mt-1">Alert when stock reaches this level</p>
        </div>
      </div>

      {/* Color */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Color Hex Code
          </label>
          <div className="flex gap-2">
            <input
              type="text"
              value={formData.colorHex}
              onChange={(e) => handleChange('colorHex', e.target.value)}
              className="flex-1 px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#CBB57B] focus:border-transparent text-sm"
              placeholder="#000000"
              maxLength={7}
            />
            <div
              className="w-10 h-10 rounded border-2 border-gray-300 flex-shrink-0"
              style={{ backgroundColor: formData.colorHex || '#f3f4f6' }}
              title={formData.colorHex || 'No color set'}
            />
          </div>
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Color Name
          </label>
          <input
            type="text"
            value={formData.colorName}
            onChange={(e) => handleChange('colorName', e.target.value)}
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#CBB57B] focus:border-transparent text-sm"
            placeholder="e.g., Midnight Black"
          />
        </div>
      </div>

      {/* Variant Image - Full Width */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-2">
          Variant Image
        </label>
        <div className="max-w-2xl">
          <EnhancedImageUpload
            onImagesChange={handleImageChange}
            initialImages={formData.image ? [formData.image] : []}
            maxImages={1}
            folder="products/variants"
          />
        </div>
      </div>

      {/* Availability */}
      <div>
        <label className="flex items-center gap-2 cursor-pointer">
          <input
            type="checkbox"
            checked={formData.isAvailable}
            onChange={(e) => handleChange('isAvailable', e.target.checked)}
            className="w-4 h-4 text-[#CBB57B] border-gray-300 rounded focus:ring-[#CBB57B]"
          />
          <span className="text-sm font-medium text-gray-700">
            Available for purchase
          </span>
        </label>
        <p className="text-xs text-gray-500 mt-1 ml-6">
          Uncheck to hide this variant from customers without deleting it
        </p>
      </div>

      {/* Actions */}
      <div className="flex items-center gap-3 pt-2">
        <button
          type="button"
          onClick={(e) => handleSubmit(e as any)}
          disabled={loading}
          className="px-4 py-2 bg-[#CBB57B] text-black font-medium rounded-lg hover:bg-[#a89158] transition-colors disabled:opacity-50 text-sm"
        >
          {loading ? 'Saving...' : variant ? 'Update Variant' : 'Create Variant'}
        </button>
        <button
          type="button"
          onClick={onCancel}
          disabled={loading}
          className="px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors disabled:opacity-50 text-sm"
        >
          Cancel
        </button>
      </div>
    </div>
  );
}
