'use client';

import React, { useState, useEffect } from 'react';
import { AdminRoute } from '@/components/admin-route';
import { AdminLayout } from '@/components/admin/admin-layout';
import PageHeader from '@/components/admin/page-header';
import { useCategories } from '@/hooks/use-admin';
import { useCategoryTree } from '@/hooks/use-categories';
import { adminCategoriesApi, type Category } from '@/lib/api/admin';
import { toast, standardToasts } from '@/lib/utils/toast';
import { Link2, X, ChevronRight, ChevronDown } from 'lucide-react';
import { useTranslations } from 'next-intl';

// Helper function to generate slug from name
function generateSlug(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

// Helper function to build parent category options recursively with indentation
function buildParentOptions(
  categories: Category[],
  editingId: string | null,
  depth: number = 0
): React.ReactElement[] {
  const options: React.ReactElement[] = [];

  // Get categories at this level (based on parent relationship)
  const categoriesAtLevel = categories.filter((c) => {
    if (depth === 0) return !c.parentId;
    return false; // This will be handled by the recursive call
  });

  // Recursive function to build options for a category and its children
  const buildOptionsForCategory = (
    category: Category,
    currentDepth: number
  ): React.ReactElement[] => {
    const opts: React.ReactElement[] = [];

    // Skip current category being edited (can't be its own parent)
    if (category.id === editingId) return opts;

    // Add current category with indentation
    const indent = '—'.repeat(currentDepth);
    opts.push(
      <option key={category.id} value={category.id}>
        {indent} {category.name}
      </option>
    );

    // Find and add children recursively
    const children = categories.filter((c) => c.parentId === category.id);
    children.forEach((child) => {
      opts.push(...buildOptionsForCategory(child, currentDepth + 1));
    });

    return opts;
  };

  // Build options for all top-level categories
  categoriesAtLevel.forEach((category) => {
    options.push(...buildOptionsForCategory(category, depth));
  });

  return options;
}

// Category Form Component (moved outside to prevent re-creation on every render)
interface CategoryFormProps {
  formData: Partial<Category>;
  categories: Category[];
  editingId: string | null;
  slugManuallyEdited: boolean;
  onNameChange: (name: string) => void;
  onSlugChange: (slug: string) => void;
  onFormDataChange: (data: Partial<Category>) => void;
  onSubmit: (e: React.FormEvent) => void;
  onCancel: () => void;
  isModal?: boolean;
}

const CategoryForm: React.FC<CategoryFormProps> = ({
  formData,
  categories,
  editingId,
  slugManuallyEdited,
  onNameChange,
  onSlugChange,
  onFormDataChange,
  onSubmit,
  onCancel,
  isModal = false,
}) => {
  const t = useTranslations('adminCategories');

  return (
    <form onSubmit={onSubmit} className="space-y-4">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            {t('form.name')} <span className="text-red-500">*</span>
          </label>
          <input
            type="text"
            required
            value={formData.name || ''}
            onChange={(e) => onNameChange(e.target.value)}
            className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#CBB57B] focus:border-transparent"
            placeholder={t('form.namePlaceholder')}
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            {t('form.slug')} <span className="text-red-500">*</span>
            {!slugManuallyEdited && (
              <span className="ml-2 text-xs text-green-600 font-normal">
                {t('form.autoGenerated')}
              </span>
            )}
          </label>
          <div className="relative">
            <input
              type="text"
              required
              value={formData.slug || ''}
              onChange={(e) => onSlugChange(e.target.value)}
              className="w-full px-4 py-2 pr-10 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#CBB57B] focus:border-transparent"
              placeholder={t('form.slugPlaceholder')}
            />
            <Link2 className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
          </div>
        </div>
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          {t('form.description')}
        </label>
        <textarea
          value={formData.description || ''}
          onChange={(e) => onFormDataChange({ ...formData, description: e.target.value })}
          rows={3}
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#CBB57B] focus:border-transparent"
          placeholder={t('form.descriptionPlaceholder')}
        />
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          {t('form.parentCategory')}
        </label>
        <select
          value={formData.parentId || ''}
          onChange={(e) => onFormDataChange({ ...formData, parentId: e.target.value || undefined })}
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#CBB57B] focus:border-transparent"
        >
          <option value="">{t('form.noneTopLevel')}</option>
          {buildParentOptions(categories, editingId, 0)}
        </select>
      </div>

      {/* Visibility Section */}
      <div className="border-2 border-dashed border-gray-300 rounded-lg p-4">
        <h3 className="text-sm font-semibold text-gray-700 mb-3">{t('form.visibilityOptions')}</h3>
        <div className="grid grid-cols-2 gap-3">
          <label className="flex items-start gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={formData.showInNavbar ?? true}
              onChange={(e) => onFormDataChange({ ...formData, showInNavbar: e.target.checked })}
              className="rounded border-gray-300 text-[#CBB57B] focus:ring-[#CBB57B] mt-0.5"
            />
            <div className="flex flex-col">
              <span className="text-sm font-medium text-gray-700">{t('form.showInMegaMenu')}</span>
              <span className="text-xs text-muted-foreground text-gray-500">
                {t('form.megaMenuHelp')}
              </span>
            </div>
          </label>
          <label className="flex items-start gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={formData.showInTopBar ?? false}
              onChange={(e) => onFormDataChange({ ...formData, showInTopBar: e.target.checked })}
              className="rounded border-gray-300 text-[#CBB57B] focus:ring-[#CBB57B] mt-0.5"
            />
            <div className="flex flex-col">
              <span className="text-sm font-medium text-gray-700">
                {t('form.showInCategoryBar')}
              </span>
              <span className="text-xs text-muted-foreground text-gray-500">
                {t('form.categoryBarHelp')}
              </span>
            </div>
          </label>
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={formData.showInSidebar ?? false}
              onChange={(e) => onFormDataChange({ ...formData, showInSidebar: e.target.checked })}
              className="rounded border-gray-300 text-[#CBB57B] focus:ring-[#CBB57B]"
            />
            <span className="text-sm font-medium text-gray-700">{t('form.showInSidebar')}</span>
          </label>
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={formData.showOnHomepage ?? false}
              onChange={(e) => onFormDataChange({ ...formData, showOnHomepage: e.target.checked })}
              className="rounded border-gray-300 text-[#CBB57B] focus:ring-[#CBB57B]"
            />
            <span className="text-sm font-medium text-gray-700">{t('form.showOnHomepage')}</span>
          </label>
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={formData.showInFooter ?? false}
              onChange={(e) => onFormDataChange({ ...formData, showInFooter: e.target.checked })}
              className="rounded border-gray-300 text-[#CBB57B] focus:ring-[#CBB57B]"
            />
            <span className="text-sm font-medium text-gray-700">{t('form.showInFooter')}</span>
          </label>
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={formData.isFeatured ?? false}
              onChange={(e) => onFormDataChange({ ...formData, isFeatured: e.target.checked })}
              className="rounded border-gray-300 text-[#CBB57B] focus:ring-[#CBB57B]"
            />
            <span className="text-sm font-medium text-gray-700">{t('form.featured')}</span>
          </label>
        </div>
      </div>

      <div className="flex items-center gap-3 pt-2">
        <button
          type="submit"
          className="px-6 py-2 bg-[#CBB57B] text-black font-medium rounded-lg hover:bg-[#a89158] transition-colors shadow"
        >
          {editingId ? t('form.updateCategory') : t('form.createCategory')}
        </button>
        <button
          type="button"
          onClick={onCancel}
          className="px-6 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors"
        >
          {t('form.cancel')}
        </button>
      </div>
    </form>
  );
};

// Recursive Category Tree Row Component
interface CategoryTreeRowProps {
  category: Category;
  depth: number;
  expandedCategories: Set<string>;
  toggleExpand: (id: string) => void;
  handleEdit: (category: Category) => void;
  handleDelete: (id: string) => void;
  t: any;
  allCategories: Category[];
}

const CategoryTreeRow: React.FC<CategoryTreeRowProps> = ({
  category,
  depth,
  expandedCategories,
  toggleExpand,
  handleEdit,
  handleDelete,
  t,
  allCategories,
}) => {
  const children = allCategories.filter((c) => c.parentId === category.id);
  const hasChildren = children.length > 0;
  const isExpanded = expandedCategories.has(category.id);
  const isTopLevel = depth === 0;

  return (
    <>
      <tr
        className={`group transition-all duration-200 ${depth > 0 ? 'bg-neutral-50/50 hover:bg-neutral-100/70' : 'hover:bg-neutral-50'}`}
      >
        {/* Name with expand/collapse and depth indicator */}
        <td className="px-6 py-3">
          <div className="flex items-center" style={{ paddingLeft: `${depth * 24}px` }}>
            {/* Tree connector for nested items */}
            {depth > 0 && (
              <div className="flex items-end mr-2" style={{ width: '20px', height: '20px' }}>
                <div
                  className="border-l-2 border-b-2 border-neutral-300 rounded-bl h-3"
                  style={{ width: '16px' }}
                ></div>
              </div>
            )}

            {/* Expand/collapse button or spacer */}
            {hasChildren ? (
              <button
                onClick={() => toggleExpand(category.id)}
                className="p-1 hover:bg-neutral-200 rounded transition-colors mr-2"
                title={isExpanded ? t('table.collapse') : t('table.expand')}
              >
                {isExpanded ? (
                  <ChevronDown className="w-4 h-4 text-neutral-600" />
                ) : (
                  <ChevronRight className="w-4 h-4 text-neutral-600" />
                )}
              </button>
            ) : (
              <span className="w-6 mr-2" />
            )}

            <span
              className={`text-sm ${isTopLevel ? 'font-semibold text-black' : 'font-medium text-neutral-700'} group-hover:text-[#CBB57B] transition-colors`}
            >
              {category.name}
            </span>

            {/* Children count badge */}
            {hasChildren && (
              <span
                className="inline-flex items-center justify-center px-1.5 py-0.5 ml-2 text-xs font-bold text-[#CBB57B] bg-[#CBB57B]/10 rounded"
                title={`${children.length} ${children.length > 1 ? t('table.subcategories') : t('table.subcategory')}`}
              >
                {children.length}
              </span>
            )}

            {/* Depth level badge */}
            <span className="inline-flex items-center justify-center px-1.5 py-0.5 ml-2 text-xs font-medium text-gray-600 bg-gray-100 rounded">
              L{depth + 1}
            </span>
          </div>
        </td>

        {/* Slug */}
        <td className="px-6 py-3">
          <span
            className={`font-mono text-xs px-2 py-1 rounded ${depth > 0 ? 'bg-neutral-200 text-neutral-600' : 'bg-neutral-100 text-neutral-700'}`}
          >
            {category.slug}
          </span>
        </td>

        {/* Products count */}
        <td className="px-6 py-3 text-center">
          <span
            className={`inline-flex items-center justify-center min-w-[2rem] px-2 py-0.5 text-xs font-bold rounded-full ${
              category.productCount > 0
                ? 'bg-blue-100 text-blue-700'
                : 'bg-neutral-100 text-neutral-500'
            }`}
          >
            {category.productCount}
          </span>
        </td>

        {/* Visibility badges */}
        <td className="px-6 py-3">
          <div className="flex flex-wrap items-center gap-1">
            {category.showInNavbar && (
              <span className="px-2 py-0.5 text-xs font-medium bg-green-100 text-green-700 rounded">
                {t('visibility.menu')}
              </span>
            )}
            {category.showInTopBar && (
              <span className="px-2 py-0.5 text-xs font-medium bg-indigo-100 text-indigo-700 rounded">
                {t('visibility.catBar')}
              </span>
            )}
            {category.showInSidebar && (
              <span className="px-2 py-0.5 text-xs font-medium bg-teal-100 text-teal-700 rounded">
                {t('visibility.sidebar')}
              </span>
            )}
            {category.showInFooter && (
              <span className="px-2 py-0.5 text-xs font-medium bg-purple-100 text-purple-700 rounded">
                {t('visibility.footer')}
              </span>
            )}
            {category.showOnHomepage && (
              <span className="px-2 py-0.5 text-xs font-medium bg-blue-100 text-blue-700 rounded">
                {t('visibility.home')}
              </span>
            )}
            {category.isFeatured && (
              <span className="px-2 py-0.5 text-xs font-medium bg-amber-100 text-amber-700 rounded">
                {t('visibility.featured')}
              </span>
            )}
            {!category.showInNavbar &&
              !category.showInTopBar &&
              !category.showInSidebar &&
              !category.showInFooter &&
              !category.showOnHomepage &&
              !category.isFeatured && <span className="text-xs text-neutral-400">-</span>}
          </div>
        </td>

        {/* Actions */}
        <td className="px-6 py-3">
          <div className="flex items-center justify-center gap-2">
            <button
              onClick={() => handleEdit(category)}
              className="p-2 hover:bg-blue-50 text-blue-600 hover:text-blue-700 rounded-lg transition-all"
              title={t('table.editCategory')}
            >
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
                />
              </svg>
            </button>
            <button
              onClick={() => handleDelete(category.id)}
              className="p-2 hover:bg-red-50 text-red-600 hover:text-red-700 rounded-lg transition-all"
              title={
                hasChildren || category.productCount > 0
                  ? `${t('table.hasDependencies')} ${children.length} ${children.length !== 1 ? t('table.subcategories') : t('table.subcategory')}, ${category.productCount} ${category.productCount !== 1 ? t('table.products_other') : t('table.product')}`
                  : t('table.deleteCategory')
              }
            >
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
                />
              </svg>
            </button>
          </div>
        </td>
      </tr>

      {/* Recursively render children */}
      {isExpanded &&
        children.map((child) => (
          <CategoryTreeRow
            key={child.id}
            category={child}
            depth={depth + 1}
            expandedCategories={expandedCategories}
            toggleExpand={toggleExpand}
            handleEdit={handleEdit}
            handleDelete={handleDelete}
            t={t}
            allCategories={allCategories}
          />
        ))}
    </>
  );
};

function CategoriesContent() {
  const t = useTranslations('adminCategories');
  const { categories, loading, refetch } = useCategories();
  const [isCreating, setIsCreating] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [slugManuallyEdited, setSlugManuallyEdited] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);
  const [expandedCategories, setExpandedCategories] = useState<Set<string>>(new Set());
  const [searchInput, setSearchInput] = useState('');
  const [statusFilter, setStatusFilter] = useState('');
  const [parentFilter, setParentFilter] = useState('');
  const [formData, setFormData] = useState<Partial<Category>>({
    name: '',
    slug: '',
    description: '',
    parentId: undefined,
    showInNavbar: true,
    showInTopBar: false,
    showInSidebar: false,
    showInFooter: false,
    showOnHomepage: false,
    isFeatured: false,
  });

  // Calculate stats
  const stats = React.useMemo(() => {
    const totalCategories = categories.length;
    const activeCategories = categories.filter(
      (c) => c.showInNavbar || c.showInTopBar || c.showInSidebar
    ).length;
    const withProducts = categories.filter((c) => (c.productCount || 0) > 0).length;
    const emptyCategories = categories.filter((c) => (c.productCount || 0) === 0).length;
    return { totalCategories, activeCategories, withProducts, emptyCategories };
  }, [categories]);

  // Filter categories
  const filteredCategories = React.useMemo(() => {
    return categories.filter((cat) => {
      // Search filter
      if (searchInput) {
        const searchLower = searchInput.toLowerCase();
        if (
          !cat.name.toLowerCase().includes(searchLower) &&
          !cat.slug.toLowerCase().includes(searchLower)
        ) {
          return false;
        }
      }
      // Status filter
      if (
        statusFilter === 'active' &&
        !cat.showInNavbar &&
        !cat.showInTopBar &&
        !cat.showInSidebar
      ) {
        return false;
      }
      if (
        statusFilter === 'inactive' &&
        (cat.showInNavbar || cat.showInTopBar || cat.showInSidebar)
      ) {
        return false;
      }
      // Parent filter
      if (parentFilter === 'root' && cat.parentId) {
        return false;
      }
      if (parentFilter === 'child' && !cat.parentId) {
        return false;
      }
      return true;
    });
  }, [categories, searchInput, statusFilter, parentFilter]);

  // Active filters
  const hasActiveFilters = searchInput || statusFilter || parentFilter;
  const activeFilterCount = [searchInput, statusFilter, parentFilter].filter(Boolean).length;

  const clearFilters = () => {
    setSearchInput('');
    setStatusFilter('');
    setParentFilter('');
  };

  // Toggle expand/collapse for parent categories
  const toggleExpand = (categoryId: string) => {
    setExpandedCategories((prev) => {
      const next = new Set(prev);
      if (next.has(categoryId)) {
        next.delete(categoryId);
      } else {
        next.add(categoryId);
      }
      return next;
    });
  };

  // Build category tree structure
  const buildCategoryTree = () => {
    const parentCategories = filteredCategories.filter((c) => !c.parentId);
    const childrenMap = new Map<string, Category[]>();

    filteredCategories.forEach((c) => {
      if (c.parentId) {
        const siblings = childrenMap.get(c.parentId) || [];
        siblings.push(c);
        childrenMap.set(c.parentId, siblings);
      }
    });

    return { parentCategories, childrenMap };
  };

  // Auto-generate slug when name changes (unless user manually edited it)
  const handleNameChange = (name: string) => {
    if (!slugManuallyEdited) {
      setFormData({ ...formData, name, slug: generateSlug(name) });
    } else {
      setFormData({ ...formData, name });
    }
  };

  const handleSlugChange = (slug: string) => {
    setSlugManuallyEdited(true);
    setFormData({ ...formData, slug });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    try {
      // Clean up data by removing empty/undefined values
      const cleanData = Object.fromEntries(
        Object.entries(formData).filter(([_, value]) => value !== undefined && value !== '')
      );

      console.log('Submitting category data:', cleanData);

      if (editingId) {
        const result = await adminCategoriesApi.update(editingId, cleanData);
        console.log('Update result:', result);
        toast.success(t('toast.categoryUpdated'));
        setShowEditModal(false);
      } else {
        const result = await adminCategoriesApi.create(cleanData);
        console.log('Create result:', result);
        toast.success(t('toast.categoryCreated'));
        setIsCreating(false);
      }

      // Reset form state
      setEditingId(null);
      setSlugManuallyEdited(false);
      setFormData({
        name: '',
        slug: '',
        description: '',
        parentId: undefined,
        showInNavbar: true,
        showInTopBar: false,
        showInSidebar: false,
        showInFooter: false,
        showOnHomepage: false,
        isFeatured: false,
      });

      // Refetch categories to update the list
      console.log('Refetching categories...');
      await refetch();
      console.log('Categories refetched successfully');
    } catch (error: any) {
      console.error('Failed to save category:', error);
      console.error('Error details:', {
        message: error.message,
        response: error.response,
        data: error.data,
        status: error.status,
      });

      // Extract user-friendly error message
      let errorMessage =
        error.message ||
        error.data?.message ||
        error.response?.data?.message ||
        t('toast.errorSave');

      // Clean up Prisma error messages
      if (errorMessage.includes('Unique constraint failed on the fields: (`slug`)')) {
        errorMessage = t('toast.slugExists');
      } else if (errorMessage.includes('Unique constraint')) {
        errorMessage = t('toast.alreadyExists');
      } else if (errorMessage.includes('Invalid `this.prisma')) {
        // Extract just the relevant error part
        const match = errorMessage.match(/constraint failed on the fields: \(`([^`]+)`\)/);
        if (match) {
          errorMessage = t('toast.fieldExists', { field: match[1] });
        } else {
          errorMessage = t('toast.databaseConstraint');
        }
      }

      toast.error(errorMessage);
    }
  };

  const handleEdit = (category: Category) => {
    setEditingId(category.id);
    setFormData({
      name: category.name,
      slug: category.slug,
      description: category.description,
      parentId: category.parentId,
      showInNavbar: category.showInNavbar ?? true,
      showInTopBar: category.showInTopBar ?? false,
      showInSidebar: category.showInSidebar ?? false,
      showInFooter: category.showInFooter ?? false,
      showOnHomepage: category.showOnHomepage ?? false,
      isFeatured: category.isFeatured ?? false,
    });
    setSlugManuallyEdited(false); // Allow auto-slug in edit mode
    setShowEditModal(true);
  };

  const handleDelete = async (id: string) => {
    const category = categories.find((c) => c.id === id);
    if (!category) return;

    // Count children (subcategories)
    const childrenCount = categories.filter((c) => c.parentId === id).length;
    const productCount = category.productCount || 0;

    // Build confirmation message
    let message = t('delete.confirmTitle', { name: category.name });
    const warnings: string[] = [];

    if (childrenCount > 0) {
      warnings.push(
        `${childrenCount} ${childrenCount > 1 ? t('table.subcategories') : t('table.subcategory')}`
      );
    }
    if (productCount > 0) {
      warnings.push(
        `${productCount} ${productCount > 1 ? t('table.products_other') : t('table.product')}`
      );
    }

    if (warnings.length > 0) {
      message += `\n\n⚠️ ${t('delete.warningHas')}\n- ${warnings.join('\n- ')}\n\n${t('delete.mustDeleteFirst')}`;
      alert(message);
      return;
    }

    // Final confirmation for clean delete
    if (!confirm(message + '\n\n' + t('delete.cannotUndo'))) {
      return;
    }

    try {
      await adminCategoriesApi.delete(id);
      toast.success(t('toast.categoryDeleted'));
      refetch();
    } catch (error: any) {
      console.error('Delete error:', error);

      // Extract user-friendly error message
      let errorMessage =
        error.message ||
        error.data?.message ||
        error.response?.data?.message ||
        t('toast.errorDelete');

      // Handle specific error cases
      if (errorMessage.includes('subcategories')) {
        const count = childrenCount;
        errorMessage = t('delete.cannotDeleteWithSubcategories', { count });
      } else if (errorMessage.includes('products')) {
        errorMessage = t('delete.cannotDeleteWithProducts', { count: productCount });
      }

      toast.error(errorMessage);
    }
  };

  const handleCancel = () => {
    setIsCreating(false);
    setEditingId(null);
    setShowEditModal(false);
    setSlugManuallyEdited(false);
    setFormData({
      name: '',
      slug: '',
      description: '',
      parentId: undefined,
      showInNavbar: true,
      showInTopBar: false,
      showInSidebar: false,
      showInFooter: false,
      showOnHomepage: false,
      isFeatured: false,
    });
  };

  const handleVisibilityToggle = async (id: string, field: string, value: boolean) => {
    try {
      await adminCategoriesApi.updateVisibility(id, { [field]: value });
      toast.success(t('toast.visibilityUpdated'));
      refetch();
    } catch (error) {
      toast.error(t('toast.errorVisibility'));
    }
  };

  return (
    <>
      <PageHeader title={t('pageTitle')} description={t('pageSubtitle')} />

      <div className="px-4 sm:px-6 lg:px-8 py-8 space-y-6">
        <div className="flex items-center justify-end">
          <button
            onClick={() => {
              setIsCreating(true);
              setSlugManuallyEdited(false);
            }}
            className="flex items-center gap-2 px-4 py-2.5 bg-[#CBB57B] text-black font-medium rounded-lg hover:bg-[#a89158] transition-colors shadow-lg"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M12 4v16m8-8H4"
              />
            </svg>
            {t('addCategory')}
          </button>
        </div>

        {/* Stats Cards */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div className="bg-white rounded-xl shadow-sm border border-neutral-200 p-6">
            <div className="flex items-center justify-between">
              <div className="flex-1">
                <p className="text-sm text-neutral-600 mb-1">{t('stats.totalCategories')}</p>
                <p className="text-2xl font-bold text-black">{stats.totalCategories}</p>
              </div>
              <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center">
                <svg
                  className="w-6 h-6 text-blue-600"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z"
                  />
                </svg>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-xl shadow-sm border border-neutral-200 p-6">
            <div className="flex items-center justify-between">
              <div className="flex-1">
                <p className="text-sm text-neutral-600 mb-1">{t('stats.active')}</p>
                <p className="text-2xl font-bold text-black">{stats.activeCategories}</p>
              </div>
              <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center">
                <svg
                  className="w-6 h-6 text-green-600"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
                  />
                </svg>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-xl shadow-sm border border-neutral-200 p-6">
            <div className="flex items-center justify-between">
              <div className="flex-1">
                <p className="text-sm text-neutral-600 mb-1">{t('stats.withProducts')}</p>
                <p className="text-2xl font-bold text-black">{stats.withProducts}</p>
              </div>
              <div className="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center">
                <svg
                  className="w-6 h-6 text-purple-600"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"
                  />
                </svg>
              </div>
            </div>
          </div>

          <div
            className={`bg-white rounded-xl shadow-sm border p-6 ${stats.emptyCategories > 0 ? 'border-amber-200 bg-amber-50/30' : 'border-neutral-200'}`}
          >
            <div className="flex items-center justify-between">
              <div className="flex-1">
                <p className="text-sm text-neutral-600 mb-1">{t('stats.emptyCategories')}</p>
                <p
                  className={`text-2xl font-bold ${stats.emptyCategories > 0 ? 'text-amber-600' : 'text-black'}`}
                >
                  {stats.emptyCategories}
                </p>
              </div>
              <div
                className={`w-12 h-12 rounded-lg flex items-center justify-center ${stats.emptyCategories > 0 ? 'bg-amber-100' : 'bg-neutral-100'}`}
              >
                <svg
                  className={`w-6 h-6 ${stats.emptyCategories > 0 ? 'text-amber-600' : 'text-neutral-600'}`}
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M5 19a2 2 0 01-2-2V7a2 2 0 012-2h4l2 2h4a2 2 0 012 2v1M5 19h14a2 2 0 002-2v-5a2 2 0 00-2-2H9a2 2 0 00-2 2v5a2 2 0 01-2 2z"
                  />
                </svg>
              </div>
            </div>
          </div>
        </div>

        {/* Filter Bar */}
        <div className="bg-white rounded-xl shadow-sm border border-neutral-200 p-6">
          <div className="flex flex-wrap items-center gap-4">
            {/* Search */}
            <div className="flex-1 min-w-[200px] relative">
              <svg
                className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-neutral-400"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                />
              </svg>
              <input
                type="text"
                placeholder={t('filters.searchPlaceholder')}
                value={searchInput}
                onChange={(e) => setSearchInput(e.target.value)}
                className="w-full pl-10 pr-10 py-2 bg-white border border-neutral-300 text-black placeholder-neutral-400 rounded-lg focus:ring-2 focus:ring-[#CBB57B] focus:border-transparent transition-all"
              />
              {searchInput && (
                <button
                  onClick={() => setSearchInput('')}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-neutral-400 hover:text-neutral-600"
                >
                  <X className="w-4 h-4" />
                </button>
              )}
            </div>

            {/* Status Filter */}
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              className="px-4 py-2 bg-white border border-neutral-300 text-black rounded-lg focus:ring-2 focus:ring-[#CBB57B] focus:border-transparent transition-all"
            >
              <option value="">{t('filters.allStatus')}</option>
              <option value="active">{t('filters.active')}</option>
              <option value="inactive">{t('filters.inactive')}</option>
            </select>

            {/* Parent Filter */}
            <select
              value={parentFilter}
              onChange={(e) => setParentFilter(e.target.value)}
              className="px-4 py-2 bg-white border border-neutral-300 text-black rounded-lg focus:ring-2 focus:ring-[#CBB57B] focus:border-transparent transition-all"
            >
              <option value="">{t('filters.allLevels')}</option>
              <option value="root">{t('filters.rootLevel')}</option>
              <option value="child">{t('filters.hasParent')}</option>
            </select>

            {/* Clear Filters */}
            {hasActiveFilters && (
              <button
                onClick={clearFilters}
                className="px-4 py-2 text-sm text-neutral-600 hover:text-neutral-900 transition-colors flex items-center gap-1"
              >
                <X className="w-4 h-4" />
                {t('filters.clear')} ({activeFilterCount})
              </button>
            )}
          </div>

          {/* Active Filter Pills */}
          {hasActiveFilters && (
            <div className="flex flex-wrap gap-2 mt-4 pt-4 border-t border-neutral-200">
              {searchInput && (
                <span className="inline-flex items-center gap-1.5 px-3 py-1 bg-neutral-100 text-neutral-700 rounded-lg text-sm">
                  {t('filters.searchLabel')} "{searchInput}"
                  <button onClick={() => setSearchInput('')} className="hover:text-neutral-900">
                    <X className="w-3 h-3" />
                  </button>
                </span>
              )}
              {statusFilter && (
                <span className="inline-flex items-center gap-1.5 px-3 py-1 bg-neutral-100 text-neutral-700 rounded-lg text-sm">
                  {t('filters.statusLabel')} {statusFilter}
                  <button onClick={() => setStatusFilter('')} className="hover:text-neutral-900">
                    <X className="w-3 h-3" />
                  </button>
                </span>
              )}
              {parentFilter && (
                <span className="inline-flex items-center gap-1.5 px-3 py-1 bg-neutral-100 text-neutral-700 rounded-lg text-sm">
                  {t('filters.levelLabel')}{' '}
                  {parentFilter === 'root' ? t('filters.rootLevel') : t('filters.hasParent')}
                  <button onClick={() => setParentFilter('')} className="hover:text-neutral-900">
                    <X className="w-3 h-3" />
                  </button>
                </span>
              )}
            </div>
          )}
        </div>

        {/* Create Form - Collapsible */}
        {isCreating && !editingId && (
          <div className="bg-white rounded-lg shadow-lg p-6 border-2 border-[#CBB57B]/30 animate-slide-in-down">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-semibold text-gray-900">{t('form.createTitle')}</h2>
              <button
                onClick={handleCancel}
                className="p-1 hover:bg-gray-100 rounded-full transition-colors"
              >
                <X className="w-5 h-5 text-gray-500" />
              </button>
            </div>
            <CategoryForm
              formData={formData}
              categories={categories}
              editingId={editingId}
              slugManuallyEdited={slugManuallyEdited}
              onNameChange={handleNameChange}
              onSlugChange={handleSlugChange}
              onFormDataChange={setFormData}
              onSubmit={handleSubmit}
              onCancel={handleCancel}
            />
          </div>
        )}

        {/* Edit Modal */}
        {showEditModal && editingId && (
          <div
            className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-[9999] p-4 animate-fade-in"
            onClick={(e) => {
              // Close modal when clicking backdrop
              if (e.target === e.currentTarget) {
                handleCancel();
              }
            }}
            onKeyDown={(e) => {
              // Close modal on Escape key
              if (e.key === 'Escape') {
                handleCancel();
              }
            }}
          >
            <div className="bg-white rounded-xl shadow-2xl max-w-3xl w-full max-h-[90vh] overflow-hidden animate-scale-in">
              {/* Sticky Header */}
              <div className="sticky top-0 bg-gradient-to-r from-[#CBB57B]/10 to-white border-b border-gray-200 px-6 py-4 flex items-center justify-between z-10">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-[#CBB57B]/20 flex items-center justify-center">
                    <svg
                      className="w-5 h-5 text-[#CBB57B]"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
                      />
                    </svg>
                  </div>
                  <div>
                    <h2 className="text-xl font-bold text-gray-900">{t('form.editTitle')}</h2>
                    <p className="text-sm text-gray-500">{t('form.editSubtitle')}</p>
                  </div>
                </div>
                <button
                  onClick={handleCancel}
                  className="p-2 hover:bg-gray-100 rounded-full transition-all hover:rotate-90 duration-300"
                  title="Close (Esc)"
                >
                  <X className="w-5 h-5 text-gray-500" />
                </button>
              </div>

              {/* Scrollable Content */}
              <div className="p-6 overflow-y-auto max-h-[calc(90vh-80px)]">
                <CategoryForm
                  formData={formData}
                  categories={categories}
                  editingId={editingId}
                  slugManuallyEdited={slugManuallyEdited}
                  onNameChange={handleNameChange}
                  onSlugChange={handleSlugChange}
                  onFormDataChange={setFormData}
                  onSubmit={handleSubmit}
                  onCancel={handleCancel}
                  isModal
                />
              </div>
            </div>
          </div>
        )}

        {/* Categories List */}
        <div className="relative bg-white rounded-2xl shadow-lg border border-neutral-200 overflow-hidden">
          {/* Subtle top accent */}
          <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-transparent via-[#CBB57B] to-transparent"></div>

          <div className="overflow-x-auto relative">
            {loading ? (
              <div className="p-16 text-center">
                <div className="relative w-16 h-16 mx-auto">
                  <div className="absolute inset-0 rounded-full border-4 border-neutral-200"></div>
                  <div className="absolute inset-0 rounded-full border-4 border-[#CBB57B] border-t-transparent animate-spin"></div>
                </div>
                <p className="mt-4 text-neutral-700 font-semibold">{t('loading')}</p>
              </div>
            ) : filteredCategories.length === 0 ? (
              <div className="p-16 text-center">
                <svg
                  className="w-16 h-16 mx-auto text-neutral-400 mb-4"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={1.5}
                    d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z"
                  />
                </svg>
                <p className="text-neutral-600 font-medium">{t('empty.noCategories')}</p>
                <p className="text-neutral-500 text-sm mt-2">
                  {hasActiveFilters ? t('empty.tryAdjusting') : t('empty.clickToCreate')}
                </p>
              </div>
            ) : (
              <table className="w-full">
                <thead>
                  <tr className="border-b-2 border-neutral-200 bg-neutral-50">
                    <th className="px-6 py-3 text-left text-xs font-bold uppercase tracking-wider">
                      <div className="flex items-center gap-2 text-black">{t('table.name')}</div>
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-bold uppercase tracking-wider">
                      <div className="flex items-center gap-2 text-black">{t('table.slug')}</div>
                    </th>
                    <th className="px-6 py-3 text-center text-xs font-bold uppercase tracking-wider">
                      <div className="flex items-center justify-center gap-2 text-black">
                        {t('table.products')}
                      </div>
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-bold uppercase tracking-wider">
                      <div className="flex items-center gap-2 text-black">
                        {t('table.visibility')}
                      </div>
                    </th>
                    <th className="px-6 py-3 text-center text-xs font-bold uppercase tracking-wider">
                      <div className="flex items-center justify-center gap-2 text-black">
                        {t('table.actions')}
                      </div>
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-neutral-200">
                  {(() => {
                    // Get root categories (those without parents)
                    const rootCategories = filteredCategories.filter((c) => !c.parentId);

                    return rootCategories.map((rootCategory) => {
                      return (
                        <CategoryTreeRow
                          key={rootCategory.id}
                          category={rootCategory}
                          depth={0}
                          expandedCategories={expandedCategories}
                          toggleExpand={toggleExpand}
                          handleEdit={handleEdit}
                          handleDelete={handleDelete}
                          t={t}
                          allCategories={filteredCategories}
                        />
                      );
                    });
                  })()}
                </tbody>
              </table>
            )}
          </div>

          {/* Bottom accent border */}
          <div className="h-1 bg-gradient-to-r from-transparent via-[#CBB57B]/50 to-transparent"></div>
        </div>
      </div>
    </>
  );
}

export default function CategoriesPage() {
  return (
    <AdminRoute>
      <AdminLayout>
        <CategoriesContent />
      </AdminLayout>
    </AdminRoute>
  );
}
