-- AlterEnum: Add NEWSLETTER_SUBSCRIBERS and ALL_INCLUDING_NEWSLETTER to CampaignAudience
ALTER TYPE "CampaignAudience" ADD VALUE 'NEWSLETTER_SUBSCRIBERS';
ALTER TYPE "CampaignAudience" ADD VALUE 'ALL_INCLUDING_NEWSLETTER';
