import { PrismaClient, SettingValueType } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Seed default system settings for NextPik E-commerce Platform
 */

const defaultSettings = [
  // GENERAL / SYSTEM SETTINGS
  {
    key: 'site_name',
    category: 'general',
    value: 'NextPik E-commerce',
    valueType: SettingValueType.STRING,
    label: 'Site Name',
    description: 'The name of your e-commerce platform',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 'NextPik E-commerce',
  },
  {
    key: 'site_tagline',
    category: 'general',
    value: 'Where Elegance Meets Excellence',
    valueType: SettingValueType.STRING,
    label: 'Site Tagline',
    description: 'A short tagline for your brand',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 'Where Elegance Meets Excellence',
  },
  {
    key: 'contact_email',
    category: 'general',
    value: 'support@luxury.com',
    valueType: SettingValueType.STRING,
    label: 'Contact Email',
    description: 'Primary contact email address',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 'support@luxury.com',
  },
  {
    key: 'timezone',
    category: 'general',
    value: 'America/New_York',
    valueType: SettingValueType.STRING,
    label: 'Timezone',
    description: 'Default timezone for the platform',
    isPublic: false,
    isEditable: true,
    requiresRestart: true,
    defaultValue: 'America/New_York',
  },
  {
    key: 'maintenance_mode',
    category: 'general',
    value: false,
    valueType: SettingValueType.BOOLEAN,
    label: 'Maintenance Mode',
    description: 'Enable maintenance mode (disables all transactions)',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: false,
  },
  {
    key: 'contact_phone',
    category: 'general',
    value: '+1-555-0123',
    valueType: SettingValueType.STRING,
    label: 'Contact Phone',
    description: 'Primary contact phone number',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: '+1-555-0123',
  },
  {
    key: 'allowed_countries',
    category: 'general',
    value: ['US', 'CA', 'GB', 'FR', 'DE', 'AU', 'RW'],
    valueType: SettingValueType.ARRAY,
    label: 'Allowed Countries',
    description: 'Countries where shipping and orders are allowed',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: ['US', 'CA', 'GB', 'FR', 'DE', 'AU', 'RW'],
  },

  // PAYMENT & ESCROW SETTINGS
  {
    key: 'escrow_enabled',
    category: 'payment',
    value: true,
    valueType: SettingValueType.BOOLEAN,
    label: 'Escrow Enabled',
    description: 'Enable escrow system (recommended for production)',
    isPublic: true,
    isEditable: true, // Editable but should be enabled in production
    requiresRestart: false,
    defaultValue: true,
  },
  {
    key: 'escrow_default_hold_days',
    category: 'payment',
    value: 7,
    valueType: SettingValueType.NUMBER,
    label: 'Default Escrow Hold Days',
    description: 'Number of days to hold funds after delivery confirmation',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 7,
  },
  {
    key: 'min_payout_amount',
    category: 'payment',
    value: 50,
    valueType: SettingValueType.NUMBER,
    label: 'Minimum Payout Amount',
    description: 'Minimum balance required for seller payout (USD)',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 50,
  },
  {
    key: 'payout_schedule',
    category: 'payment',
    value: 'weekly',
    valueType: SettingValueType.STRING,
    label: 'Payout Schedule',
    description: 'How often payouts are processed',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 'weekly',
  },
  {
    key: 'escrow_auto_release_enabled',
    category: 'payment',
    value: true,
    valueType: SettingValueType.BOOLEAN,
    label: 'Auto-Release Escrow',
    description: 'Automatically release funds after hold period expires',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: true,
  },
  {
    key: 'payment_methods',
    category: 'payment',
    value: ['credit_card', 'stripe', 'paypal'],
    valueType: SettingValueType.ARRAY,
    label: 'Enabled Payment Methods',
    description: 'Payment methods available for checkout',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: ['credit_card', 'stripe', 'paypal'],
  },

  // STRIPE PAYMENT INTEGRATION
  {
    key: 'stripe_enabled',
    category: 'payment',
    value: false,
    valueType: SettingValueType.BOOLEAN,
    label: 'Stripe Integration Enabled',
    description: 'Enable Stripe payment processing',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: false,
  },
  {
    key: 'stripe_test_mode',
    category: 'payment',
    value: true,
    valueType: SettingValueType.BOOLEAN,
    label: 'Stripe Test Mode',
    description: 'Use Stripe test keys (sandbox environment)',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: true,
  },
  {
    key: 'stripe_publishable_key',
    category: 'payment',
    value: '',
    valueType: SettingValueType.STRING,
    label: 'Stripe Publishable Key',
    description: 'Stripe public/publishable API key (safe to expose to frontend)',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: '',
  },
  {
    key: 'stripe_secret_key',
    category: 'payment',
    value: '',
    valueType: SettingValueType.STRING,
    label: 'Stripe Secret Key',
    description: 'Stripe secret API key (NEVER expose to frontend, encrypted in database)',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: '',
  },
  {
    key: 'stripe_webhook_secret',
    category: 'payment',
    value: '',
    valueType: SettingValueType.STRING,
    label: 'Stripe Webhook Secret',
    description: 'Stripe webhook signing secret for signature verification',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: '',
  },
  {
    key: 'stripe_webhook_url',
    category: 'payment',
    value: '',
    valueType: SettingValueType.STRING,
    label: 'Stripe Webhook URL',
    description: 'The URL where Stripe sends webhook events (auto-configured)',
    isPublic: false,
    isEditable: false,
    requiresRestart: false,
    defaultValue: '',
  },
  {
    key: 'stripe_currency',
    category: 'payment',
    value: 'USD',
    valueType: SettingValueType.STRING,
    label: 'Stripe Default Currency',
    description: 'Default currency for Stripe payment processing',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 'USD',
  },
  {
    key: 'stripe_capture_method',
    category: 'payment',
    value: 'manual',
    valueType: SettingValueType.STRING,
    label: 'Stripe Capture Method',
    description: 'Payment capture method (manual for escrow, automatic for instant capture)',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 'manual',
  },
  {
    key: 'stripe_statement_descriptor',
    category: 'payment',
    value: 'LUXURY ECOM',
    valueType: SettingValueType.STRING,
    label: 'Stripe Statement Descriptor',
    description: 'Text shown on customer credit card statements (max 22 chars)',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 'LUXURY ECOM',
  },
  {
    key: 'stripe_auto_payout_enabled',
    category: 'payment',
    value: false,
    valueType: SettingValueType.BOOLEAN,
    label: 'Stripe Auto Payout',
    description: 'Automatically transfer funds to sellers via Stripe Connect',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: false,
  },

  // COMMISSION SETTINGS
  {
    key: 'global_commission_rate',
    category: 'commission',
    value: 15,
    valueType: SettingValueType.NUMBER,
    label: 'Global Commission Rate (%)',
    description: 'Default platform commission rate (percentage)',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 15,
  },
  {
    key: 'commission_type',
    category: 'commission',
    value: 'PERCENTAGE',
    valueType: SettingValueType.STRING,
    label: 'Commission Type',
    description: 'How commission is calculated',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 'PERCENTAGE',
  },
  {
    key: 'commission_applies_to_shipping',
    category: 'commission',
    value: false,
    valueType: SettingValueType.BOOLEAN,
    label: 'Apply Commission to Shipping',
    description: 'Include shipping costs in commission calculation',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: false,
  },
  {
    key: 'commission_min_amount',
    category: 'commission',
    value: 0.50,
    valueType: SettingValueType.NUMBER,
    label: 'Minimum Commission Amount (USD)',
    description: 'Minimum commission charged per transaction regardless of rate',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 0.50,
  },
  {
    key: 'commission_max_amount',
    category: 'commission',
    value: 0,
    valueType: SettingValueType.NUMBER,
    label: 'Maximum Commission Amount (USD)',
    description: 'Maximum commission cap per transaction (0 = no maximum)',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 0,
  },
  {
    key: 'commission_fixed_fee',
    category: 'commission',
    value: 0.30,
    valueType: SettingValueType.NUMBER,
    label: 'Fixed Commission Fee (USD)',
    description: 'Fixed fee added to every transaction (similar to Stripe fee)',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 0.30,
  },

  // CURRENCY SETTINGS
  {
    key: 'default_currency',
    category: 'currency',
    value: 'USD',
    valueType: SettingValueType.STRING,
    label: 'Default Currency',
    description: 'Primary currency for the platform',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 'USD',
  },
  {
    key: 'supported_currencies',
    category: 'currency',
    value: ['USD', 'EUR', 'GBP', 'RWF'],
    valueType: SettingValueType.ARRAY,
    label: 'Supported Currencies',
    description: 'All currencies supported by the platform',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: ['USD', 'EUR', 'GBP', 'RWF'],
  },
  {
    key: 'currency_auto_sync',
    category: 'currency',
    value: true,
    valueType: SettingValueType.BOOLEAN,
    label: 'Auto-Sync Exchange Rates',
    description: 'Automatically update exchange rates',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: true,
  },
  {
    key: 'currency_sync_frequency',
    category: 'currency',
    value: 'daily',
    valueType: SettingValueType.STRING,
    label: 'Currency Sync Frequency',
    description: 'How often to sync exchange rates (hourly, daily, weekly)',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 'daily',
  },

  // TAX SETTINGS
  {
    key: 'tax_calculation_enabled',
    category: 'tax',
    value: false,
    valueType: SettingValueType.BOOLEAN,
    label: 'Dynamic Tax Calculation Enabled',
    description: 'Enable tax calculation from settings (false = use hardcoded 10%)',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: false,
  },
  {
    key: 'tax_default_rate',
    category: 'tax',
    value: 0.10,
    valueType: SettingValueType.NUMBER,
    label: 'Default Tax Rate',
    description: 'Default tax rate as decimal (e.g., 0.10 = 10%, 0.15 = 15%)',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 0.10,
  },
  {
    key: 'tax_calculation_mode',
    category: 'tax',
    value: 'disabled',
    valueType: SettingValueType.STRING,
    label: 'Tax Calculation Mode',
    description: 'How tax is calculated: disabled (no tax), simple (default rate), by_state (US state rates)',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 'disabled',
  },

  // SHIPPING SETTINGS
  {
    key: 'shipping_mode',
    category: 'shipping',
    value: 'manual',
    valueType: SettingValueType.STRING,
    label: 'Shipping Mode',
    description: 'manual: Use configured rates | dhl_api: DHL integration | hybrid: DHL with manual fallback',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 'manual',
  },
  {
    key: 'shipping_standard_rate',
    category: 'shipping',
    value: 9.99,
    valueType: SettingValueType.NUMBER,
    label: 'Standard Shipping Rate',
    description: 'Base rate for standard shipping (USD)',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 9.99,
  },
  {
    key: 'shipping_express_rate',
    category: 'shipping',
    value: 19.99,
    valueType: SettingValueType.NUMBER,
    label: 'Express Shipping Rate',
    description: 'Base rate for express shipping (USD)',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 19.99,
  },
  {
    key: 'shipping_overnight_rate',
    category: 'shipping',
    value: 29.99,
    valueType: SettingValueType.NUMBER,
    label: 'Overnight Shipping Rate',
    description: 'Base rate for overnight delivery (USD)',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 29.99,
  },
  {
    key: 'shipping_international_surcharge',
    category: 'shipping',
    value: 15.00,
    valueType: SettingValueType.NUMBER,
    label: 'International Shipping Surcharge',
    description: 'Additional fee for international orders (USD)',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 15.00,
  },

  // DELIVERY SETTINGS
  {
    key: 'delivery_confirmation_required',
    category: 'delivery',
    value: true,
    valueType: SettingValueType.BOOLEAN,
    label: 'Delivery Confirmation Required',
    description: 'Require delivery confirmation to release escrow',
    isPublic: false,
    isEditable: false,
    requiresRestart: false,
    defaultValue: true,
  },
  {
    key: 'free_shipping_enabled',
    category: 'delivery',
    value: true,
    valueType: SettingValueType.BOOLEAN,
    label: 'Free Shipping Enabled',
    description: 'Enable free shipping for orders above threshold',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: true,
  },
  {
    key: 'free_shipping_threshold',
    category: 'delivery',
    value: 200,
    valueType: SettingValueType.NUMBER,
    label: 'Free Shipping Threshold (USD)',
    description: 'Order total above which shipping is free',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 200,
  },
  {
    key: 'delivery_auto_assign',
    category: 'delivery',
    value: false,
    valueType: SettingValueType.BOOLEAN,
    label: 'Auto-Assign Deliveries',
    description: 'Automatically assign deliveries to available partners',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: false,
  },
  {
    key: 'delivery_partner_commission',
    category: 'delivery',
    value: 10,
    valueType: SettingValueType.NUMBER,
    label: 'Delivery Partner Commission (%)',
    description: 'Commission rate for delivery partners',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 10,
  },

  // DHL API INTEGRATION SETTINGS
  {
    key: 'shipping_primary_provider',
    category: 'delivery',
    value: 'DHL',
    valueType: SettingValueType.STRING,
    label: 'Primary Shipping Provider',
    description: 'Primary shipping carrier for deliveries',
    isPublic: true,
    isEditable: false,
    requiresRestart: false,
    defaultValue: 'DHL',
  },

  // NOTE: DHL API credentials (DHL_API_KEY, DHL_API_SECRET, DHL_TRACKING_ENABLED, DHL_API_BASE_URL, DHL_TRACKING_CACHE_TTL)
  // are now configured via environment variables (.env) for security reasons.
  // See apps/api/.env for DHL configuration.

  // SECURITY SETTINGS
  {
    key: '2fa_required_for_admin',
    category: 'security',
    value: true,
    valueType: SettingValueType.BOOLEAN,
    label: 'Require 2FA for Admin',
    description: 'Enforce two-factor authentication for admin',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: true,
  },
  {
    key: 'password_min_length',
    category: 'security',
    value: 8,
    valueType: SettingValueType.NUMBER,
    label: 'Minimum Password Length',
    description: 'Minimum characters required for passwords',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 8,
  },
  {
    key: 'session_timeout_minutes',
    category: 'security',
    value: 30,
    valueType: SettingValueType.NUMBER,
    label: 'Session Timeout (minutes)',
    description: 'Inactivity timeout for user sessions',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 30,
  },
  {
    key: 'max_login_attempts',
    category: 'security',
    value: 5,
    valueType: SettingValueType.NUMBER,
    label: 'Maximum Login Attempts',
    description: 'Failed login attempts before account lockout',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 5,
  },
  {
    key: 'password_require_special_chars',
    category: 'security',
    value: true,
    valueType: SettingValueType.BOOLEAN,
    label: 'Require Special Characters',
    description: 'Require special characters in passwords',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: true,
  },
  {
    key: 'allowed_file_types',
    category: 'security',
    value: ['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx'],
    valueType: SettingValueType.ARRAY,
    label: 'Allowed File Types',
    description: 'File extensions allowed for uploads',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: ['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx'],
  },
  {
    key: 'max_file_size_mb',
    category: 'security',
    value: 5,
    valueType: SettingValueType.NUMBER,
    label: 'Max File Size (MB)',
    description: 'Maximum file upload size in megabytes',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 5,
  },

  // NOTIFICATION SETTINGS
  {
    key: 'email_notifications_enabled',
    category: 'notifications',
    value: true,
    valueType: SettingValueType.BOOLEAN,
    label: 'Email Notifications',
    description: 'Enable email notifications globally',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: true,
  },
  {
    key: 'sms_notifications_enabled',
    category: 'notifications',
    value: false,
    valueType: SettingValueType.BOOLEAN,
    label: 'SMS Notifications',
    description: 'Enable SMS notifications globally',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: false,
  },
  {
    key: 'notification_events',
    category: 'notifications',
    value: [
      'order_placed',
      'order_shipped',
      'order_delivered',
      'payment_received',
      'payout_processed',
      'product_low_stock',
      'new_review',
      'account_login',
    ],
    valueType: SettingValueType.ARRAY,
    label: 'Notification Events',
    description: 'Events that trigger notifications',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: [
      'order_placed',
      'order_shipped',
      'order_delivered',
      'payment_received',
      'payout_processed',
      'product_low_stock',
      'new_review',
      'account_login',
    ],
  },

  // INVENTORY SETTINGS
  {
    key: 'inventory.low_stock_threshold',
    category: 'inventory',
    value: 10,
    valueType: SettingValueType.NUMBER,
    label: 'Low Stock Threshold',
    description: 'Stock level that triggers low stock warning',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 10,
  },
  {
    key: 'inventory.auto_sku_generation',
    category: 'inventory',
    value: true,
    valueType: SettingValueType.BOOLEAN,
    label: 'Auto-Generate SKU',
    description: 'Automatically generate SKU for new products',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: true,
  },
  {
    key: 'inventory.sku_prefix',
    category: 'inventory',
    value: 'PROD',
    valueType: SettingValueType.STRING,
    label: 'SKU Prefix',
    description: 'Prefix for auto-generated SKUs',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 'PROD',
  },
  {
    key: 'inventory.enable_stock_notifications',
    category: 'inventory',
    value: true,
    valueType: SettingValueType.BOOLEAN,
    label: 'Enable Stock Notifications',
    description: 'Send notifications when stock is low',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: true,
  },
  {
    key: 'inventory.allow_negative_stock',
    category: 'inventory',
    value: false,
    valueType: SettingValueType.BOOLEAN,
    label: 'Allow Negative Stock',
    description: 'Allow orders when inventory is zero or negative',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: false,
  },
  {
    key: 'inventory.transaction_history_page_size',
    category: 'inventory',
    value: 20,
    valueType: SettingValueType.NUMBER,
    label: 'Transaction History Page Size',
    description: 'Number of inventory transactions to display per page',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 20,
  },

  // SEO SETTINGS
  {
    key: 'seo_meta_title',
    category: 'seo',
    value: 'NextPik E-commerce - Premium Products Online',
    valueType: SettingValueType.STRING,
    label: 'SEO Meta Title',
    description: 'Default meta title for pages',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 'NextPik E-commerce - Premium Products Online',
  },
  {
    key: 'seo_meta_description',
    category: 'seo',
    value:
      'Discover our curated collection of luxury products. Premium quality, exceptional service, and secure shopping experience.',
    valueType: SettingValueType.STRING,
    label: 'SEO Meta Description',
    description: 'Default meta description for pages',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue:
      'Discover our curated collection of luxury products. Premium quality, exceptional service, and secure shopping experience.',
  },
  {
    key: 'seo_keywords',
    category: 'seo',
    value: 'luxury, premium, e-commerce, online shopping, high-end products',
    valueType: SettingValueType.STRING,
    label: 'SEO Keywords',
    description: 'Default SEO keywords (comma-separated)',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue:
      'luxury, premium, e-commerce, online shopping, high-end products',
  },
  {
    key: 'analytics_enabled',
    category: 'seo',
    value: true,
    valueType: SettingValueType.BOOLEAN,
    label: 'Analytics Enabled',
    description: 'Enable Google Analytics and tracking',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: true,
  },
];

async function seedSettings() {
  console.log('🌱 Seeding system settings...');

  for (const setting of defaultSettings) {
    await prisma.systemSetting.upsert({
      where: { key: setting.key },
      update: {
        label: setting.label,
        description: setting.description,
        isPublic: setting.isPublic,
      },
      create: setting,
    });
    console.log(`  ✓ ${setting.key}`);
  }

  console.log(`✅ Seeded ${defaultSettings.length} system settings`);
}

seedSettings()
  .catch((e) => {
    console.error('❌ Error seeding settings:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
