import { PrismaClient, SettingValueType } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Seed default system settings for Luxury E-commerce Platform
 */

const defaultSettings = [
  // GENERAL / SYSTEM SETTINGS
  {
    key: 'site_name',
    category: 'general',
    value: 'Luxury E-commerce',
    valueType: SettingValueType.STRING,
    label: 'Site Name',
    description: 'The name of your e-commerce platform',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 'Luxury E-commerce',
  },
  {
    key: 'site_tagline',
    category: 'general',
    value: 'Where Elegance Meets Excellence',
    valueType: SettingValueType.STRING,
    label: 'Site Tagline',
    description: 'A short tagline for your brand',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 'Where Elegance Meets Excellence',
  },
  {
    key: 'contact_email',
    category: 'general',
    value: 'support@luxury.com',
    valueType: SettingValueType.STRING,
    label: 'Contact Email',
    description: 'Primary contact email address',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 'support@luxury.com',
  },
  {
    key: 'timezone',
    category: 'general',
    value: 'America/New_York',
    valueType: SettingValueType.STRING,
    label: 'Timezone',
    description: 'Default timezone for the platform',
    isPublic: false,
    isEditable: true,
    requiresRestart: true,
    defaultValue: 'America/New_York',
  },
  {
    key: 'maintenance_mode',
    category: 'general',
    value: false,
    valueType: SettingValueType.BOOLEAN,
    label: 'Maintenance Mode',
    description: 'Enable maintenance mode (disables all transactions)',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: false,
  },
  {
    key: 'contact_phone',
    category: 'general',
    value: '+1-555-0123',
    valueType: SettingValueType.STRING,
    label: 'Contact Phone',
    description: 'Primary contact phone number',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: '+1-555-0123',
  },
  {
    key: 'allowed_countries',
    category: 'general',
    value: ['US', 'CA', 'GB', 'FR', 'DE', 'AU', 'RW'],
    valueType: SettingValueType.ARRAY,
    label: 'Allowed Countries',
    description: 'Countries where shipping and orders are allowed',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: ['US', 'CA', 'GB', 'FR', 'DE', 'AU', 'RW'],
  },

  // PAYMENT & ESCROW SETTINGS
  {
    key: 'escrow_enabled',
    category: 'payment',
    value: true,
    valueType: SettingValueType.BOOLEAN,
    label: 'Escrow Enabled',
    description: 'Enable escrow system (REQUIRED for production)',
    isPublic: true,
    isEditable: false,
    requiresRestart: false,
    defaultValue: true,
  },
  {
    key: 'escrow_default_hold_days',
    category: 'payment',
    value: 7,
    valueType: SettingValueType.NUMBER,
    label: 'Default Escrow Hold Days',
    description: 'Number of days to hold funds after delivery confirmation',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 7,
  },
  {
    key: 'min_payout_amount',
    category: 'payment',
    value: 50,
    valueType: SettingValueType.NUMBER,
    label: 'Minimum Payout Amount',
    description: 'Minimum balance required for seller payout (USD)',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 50,
  },
  {
    key: 'payout_schedule',
    category: 'payment',
    value: 'weekly',
    valueType: SettingValueType.STRING,
    label: 'Payout Schedule',
    description: 'How often payouts are processed',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 'weekly',
  },
  {
    key: 'escrow_auto_release_enabled',
    category: 'payment',
    value: true,
    valueType: SettingValueType.BOOLEAN,
    label: 'Auto-Release Escrow',
    description: 'Automatically release funds after hold period expires',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: true,
  },
  {
    key: 'payment_methods',
    category: 'payment',
    value: ['credit_card', 'stripe', 'paypal'],
    valueType: SettingValueType.ARRAY,
    label: 'Enabled Payment Methods',
    description: 'Payment methods available for checkout',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: ['credit_card', 'stripe', 'paypal'],
  },

  // COMMISSION SETTINGS
  {
    key: 'global_commission_rate',
    category: 'commission',
    value: 15,
    valueType: SettingValueType.NUMBER,
    label: 'Global Commission Rate (%)',
    description: 'Default platform commission rate (percentage)',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 15,
  },
  {
    key: 'commission_type',
    category: 'commission',
    value: 'PERCENTAGE',
    valueType: SettingValueType.STRING,
    label: 'Commission Type',
    description: 'How commission is calculated',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 'PERCENTAGE',
  },
  {
    key: 'commission_applies_to_shipping',
    category: 'commission',
    value: false,
    valueType: SettingValueType.BOOLEAN,
    label: 'Apply Commission to Shipping',
    description: 'Include shipping costs in commission calculation',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: false,
  },

  // CURRENCY SETTINGS
  {
    key: 'default_currency',
    category: 'currency',
    value: 'USD',
    valueType: SettingValueType.STRING,
    label: 'Default Currency',
    description: 'Primary currency for the platform',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 'USD',
  },
  {
    key: 'supported_currencies',
    category: 'currency',
    value: ['USD', 'EUR', 'GBP', 'RWF'],
    valueType: SettingValueType.ARRAY,
    label: 'Supported Currencies',
    description: 'All currencies supported by the platform',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: ['USD', 'EUR', 'GBP', 'RWF'],
  },
  {
    key: 'currency_auto_sync',
    category: 'currency',
    value: true,
    valueType: SettingValueType.BOOLEAN,
    label: 'Auto-Sync Exchange Rates',
    description: 'Automatically update exchange rates',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: true,
  },
  {
    key: 'currency_sync_frequency',
    category: 'currency',
    value: 'daily',
    valueType: SettingValueType.STRING,
    label: 'Currency Sync Frequency',
    description: 'How often to sync exchange rates (hourly, daily, weekly)',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 'daily',
  },

  // DELIVERY SETTINGS
  {
    key: 'delivery_confirmation_required',
    category: 'delivery',
    value: true,
    valueType: SettingValueType.BOOLEAN,
    label: 'Delivery Confirmation Required',
    description: 'Require delivery confirmation to release escrow',
    isPublic: false,
    isEditable: false,
    requiresRestart: false,
    defaultValue: true,
  },
  {
    key: 'free_shipping_threshold',
    category: 'delivery',
    value: 200,
    valueType: SettingValueType.NUMBER,
    label: 'Free Shipping Threshold (USD)',
    description: 'Order total above which shipping is free',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 200,
  },
  {
    key: 'delivery_auto_assign',
    category: 'delivery',
    value: false,
    valueType: SettingValueType.BOOLEAN,
    label: 'Auto-Assign Deliveries',
    description: 'Automatically assign deliveries to available partners',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: false,
  },
  {
    key: 'delivery_partner_commission',
    category: 'delivery',
    value: 10,
    valueType: SettingValueType.NUMBER,
    label: 'Delivery Partner Commission (%)',
    description: 'Commission rate for delivery partners',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 10,
  },

  // SECURITY SETTINGS
  {
    key: '2fa_required_for_admin',
    category: 'security',
    value: true,
    valueType: SettingValueType.BOOLEAN,
    label: 'Require 2FA for Admin',
    description: 'Enforce two-factor authentication for admin',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: true,
  },
  {
    key: 'password_min_length',
    category: 'security',
    value: 8,
    valueType: SettingValueType.NUMBER,
    label: 'Minimum Password Length',
    description: 'Minimum characters required for passwords',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 8,
  },
  {
    key: 'session_timeout_minutes',
    category: 'security',
    value: 30,
    valueType: SettingValueType.NUMBER,
    label: 'Session Timeout (minutes)',
    description: 'Inactivity timeout for user sessions',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 30,
  },
  {
    key: 'max_login_attempts',
    category: 'security',
    value: 5,
    valueType: SettingValueType.NUMBER,
    label: 'Maximum Login Attempts',
    description: 'Failed login attempts before account lockout',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 5,
  },
  {
    key: 'password_require_special_chars',
    category: 'security',
    value: true,
    valueType: SettingValueType.BOOLEAN,
    label: 'Require Special Characters',
    description: 'Require special characters in passwords',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: true,
  },
  {
    key: 'allowed_file_types',
    category: 'security',
    value: ['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx'],
    valueType: SettingValueType.ARRAY,
    label: 'Allowed File Types',
    description: 'File extensions allowed for uploads',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: ['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx'],
  },
  {
    key: 'max_file_size_mb',
    category: 'security',
    value: 5,
    valueType: SettingValueType.NUMBER,
    label: 'Max File Size (MB)',
    description: 'Maximum file upload size in megabytes',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 5,
  },

  // NOTIFICATION SETTINGS
  {
    key: 'email_notifications_enabled',
    category: 'notifications',
    value: true,
    valueType: SettingValueType.BOOLEAN,
    label: 'Email Notifications',
    description: 'Enable email notifications globally',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: true,
  },
  {
    key: 'sms_notifications_enabled',
    category: 'notifications',
    value: false,
    valueType: SettingValueType.BOOLEAN,
    label: 'SMS Notifications',
    description: 'Enable SMS notifications globally',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: false,
  },
  {
    key: 'notification_events',
    category: 'notifications',
    value: [
      'order_placed',
      'order_shipped',
      'order_delivered',
      'payment_received',
      'payout_processed',
      'product_low_stock',
      'new_review',
      'account_login',
    ],
    valueType: SettingValueType.ARRAY,
    label: 'Notification Events',
    description: 'Events that trigger notifications',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: [
      'order_placed',
      'order_shipped',
      'order_delivered',
      'payment_received',
      'payout_processed',
      'product_low_stock',
      'new_review',
      'account_login',
    ],
  },

  // SEO SETTINGS
  {
    key: 'seo_meta_title',
    category: 'seo',
    value: 'Luxury E-commerce - Premium Products Online',
    valueType: SettingValueType.STRING,
    label: 'SEO Meta Title',
    description: 'Default meta title for pages',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue: 'Luxury E-commerce - Premium Products Online',
  },
  {
    key: 'seo_meta_description',
    category: 'seo',
    value:
      'Discover our curated collection of luxury products. Premium quality, exceptional service, and secure shopping experience.',
    valueType: SettingValueType.STRING,
    label: 'SEO Meta Description',
    description: 'Default meta description for pages',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue:
      'Discover our curated collection of luxury products. Premium quality, exceptional service, and secure shopping experience.',
  },
  {
    key: 'seo_keywords',
    category: 'seo',
    value: 'luxury, premium, e-commerce, online shopping, high-end products',
    valueType: SettingValueType.STRING,
    label: 'SEO Keywords',
    description: 'Default SEO keywords (comma-separated)',
    isPublic: true,
    isEditable: true,
    requiresRestart: false,
    defaultValue:
      'luxury, premium, e-commerce, online shopping, high-end products',
  },
  {
    key: 'analytics_enabled',
    category: 'seo',
    value: true,
    valueType: SettingValueType.BOOLEAN,
    label: 'Analytics Enabled',
    description: 'Enable Google Analytics and tracking',
    isPublic: false,
    isEditable: true,
    requiresRestart: false,
    defaultValue: true,
  },
];

async function seedSettings() {
  console.log('🌱 Seeding system settings...');

  for (const setting of defaultSettings) {
    await prisma.systemSetting.upsert({
      where: { key: setting.key },
      update: {
        label: setting.label,
        description: setting.description,
        isPublic: setting.isPublic,
      },
      create: setting,
    });
    console.log(`  ✓ ${setting.key}`);
  }

  console.log(`✅ Seeded ${defaultSettings.length} system settings`);
}

seedSettings()
  .catch((e) => {
    console.error('❌ Error seeding settings:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
